In [38]:
# *Intro to ML Pre Codelab*
# Objectives:
# > By running this codelab successfully you'll be able to take the Intro to ML class on Thursday.
# > Learn about the basic algorithms used for ML, how they work and how they can be implemented in Python.
#
# Minimum Knowledge Required:
# > Basic Git (you can check http://rogerdudler.github.io/git-guide/)
# > You don't need to understand Python or ML :^)

import numpy as np
import sklearn as sk # This part is not used in the Pre Code Lab but will be necessary for the Intro

In [39]:
# Basic Knowledge Needed - Linear Algebra

# *Matrix operations*
# Oh no! The data input has some errors (what a surprise) and we need to change some values in the matrix.
# Let's first create the wrong matrix:

faulty_matrix = np.matrix([[1, 4, 7], [2, 7, 8], [3, 6, 10]])

print(faulty_matrix)

[[ 1  4  7]
 [ 2  7  8]
 [ 3  6 10]]


In [40]:
# Now let's fix this matrix.
faulty_matrix[1,1] = 5
faulty_matrix[2,2] = 9

print(faulty_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:
# Beautiful. But oh no! We want the 1, 2, 3 to be in the first row, not the first column! What should we do?
# Thankfully, we have the transpose function.
correct_matrix = np.transpose(faulty_matrix)

print(correct_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
# Let's say your friend Bob just asked you to give him numbers 1 to 6 excluding 1 and 4. One way to do this would be:
print(correct_matrix[0:2,1:3])

[[2 3]
 [5 6]]


In [35]:
# Now that's a weird request, but finally your friend Bob is happy. See you on Thursday!